param(
    [string]$RepositoryRoot = (Get-Location).Path,
    [switch]$Force,
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Ensure-Directory {
    param(
        [Parameter(Mandatory = $true)][string]$Path
    )

    if (-not (Test-Path -Path $Path)) {
        if ($DryRun) {
            Write-Host "[DryRun] Create directory: $Path"
            return
        }

        New-Item -ItemType Directory -Path $Path -Force | Out-Null
        Write-Host "Created directory: $Path"
    }
}

function Write-TemplateFile {
    param(
        [Parameter(Mandatory = $true)][string]$RelativePath,
        [Parameter(Mandatory = $true)][string]$Content,
        [switch]$OnlyIfMissing
    )

    $targetPath = Join-Path $RepositoryRoot $RelativePath
    $targetDir = Split-Path -Parent $targetPath
    Ensure-Directory -Path $targetDir

    $exists = Test-Path -Path $targetPath
    if ($exists -and $OnlyIfMissing -and -not $Force) {
        if ($DryRun) {
            Write-Host "[DryRun] Skip (exists): $RelativePath"
            return
        }

        Write-Host "Skipped (exists): $RelativePath"
        return
    }

    if ($exists -and -not $Force) {
        if ($DryRun) {
            Write-Host "[DryRun] Skip (exists, use -Force to overwrite): $RelativePath"
            return
        }

        Write-Host "Skipped (exists, use -Force to overwrite): $RelativePath"
        return
    }

    if ($DryRun) {
        Write-Host "[DryRun] Install: $RelativePath"
        return
    }

    Set-Content -Path $targetPath -Value $Content -Encoding UTF8
    Write-Host "Installed: $RelativePath"
}

$directories = @(
    "ai",
    "ai/prompts",
    "ai/tasks",
    "ai/tasks/pending",
    "ai/tasks/in-progress",
    "ai/tasks/done",
    "ai/orchestrator",
    "scripts",
    ".github",
    ".github/workflows"
)

foreach ($dir in $directories) {
    Ensure-Directory -Path (Join-Path $RepositoryRoot $dir)
}

$templateFiles = @{
    "ai/task-template.md" = @'
# TASK-XXX

## Goal
Clear description of the objective.

## Context
Explain where in the project the change happens.

## Steps

1. Step one
2. Step two
3. Step three

## Files to Read First

List the most relevant files that should be inspected before implementing the task.

## Expected Files to Modify

List the files that are expected to change during this task.

## Constraints

- Do not modify unrelated files
- Keep the change minimal
- Prefer small commits

## Validation

Before completing the task ensure:

- build succeeds
- tests succeed
- no new warnings introduced

## Change Budget

- Prefer modifying fewer than 5 files.
- Prefer changes under 200 lines of code.
- Split the work into additional tasks if limits are exceeded.
'@
    "ai/repo-context.md" = @'
# Repository Context

Describe the project architecture, core layers, and technical constraints used for implementation planning.
'@
    "ai/system-metrics.md" = @'
# System Metrics

This file tracks execution metrics of the AI development pipeline.

## Metrics

- Total tasks executed
- Average task duration
- Failed tasks
- Tasks generated by repository review

## Task History

Date | Task | Duration | Result
'@
    "ai/architecture-index.md" = @'
# Architecture Index

This file provides a quick overview of the repository architecture.

AI agents should read this file before scanning the repository.
'@
    "ai/orchestrator/feature-planner.md" = @'
# Feature Planner

## Purpose
Turn feature requests into implementation-ready plans and executable tasks.

## Planning Workflow
1. Read `ai/architecture-index.md`.
2. Discover relevant components and dependencies.
3. Produce a concise implementation plan.
4. Generate task files in `ai/tasks/pending`.

## Task Generation Rules
- Use `ai/task-template.md`.
- Include `## Files to Read First` and `## Expected Files to Modify` in every task.
- Keep tasks small and focused.
'@
    "ai/orchestrator/pr-generator.md" = @'
# Pull Request Generator

## PR Title
Feature: <short description>

## PR Description
### Summary
Describe the implemented feature.

### Tasks implemented
List the completed tasks.

### Validation
- build succeeded
- tests succeeded
'@
    "ai/orchestrator/repo-reviewer.md" = @'
# Repository Reviewer

Review repository health and create improvement tasks when needed.
'@
    "ai/orchestrator/planning-memory.md" = @'
# Planning Memory

Store lessons learned from previous tasks and use them during planning.
'@
    "ai/orchestrator/component-discovery.md" = @'
# Component Discovery

Identify controllers, services, models, data components, and tests related to a feature.
'@
    "ai/orchestrator/di-analysis.md" = @'
# Dependency Injection Analysis

Analyze service registrations and dependency relationships to avoid duplicate services.
'@
    "scripts/codex-runner.ps1" = @'
Write-Host "Codex worker started..."

$lockFile = "ai/worker.lock"

while ($true) {
    if (Test-Path $lockFile) {
        Write-Host "Worker already running. Waiting..."
        Start-Sleep -Seconds 30
        continue
    }

    git pull
    $tasks = Get-ChildItem "ai/tasks/pending" -Filter *.md -ErrorAction SilentlyContinue

    if ($tasks) {
        New-Item $lockFile -ItemType File | Out-Null
        codex --auto "Follow the workflow defined in AGENTS.md and process the pending tasks."
        Remove-Item $lockFile
    }

    Start-Sleep -Seconds 30
}
'@
    ".github/workflows/codex-worker.yml" = @'
name: Codex Worker

on:
  push:
    paths:
      - 'ai/tasks/pending/**'

jobs:
  run-codex-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Codex CLI
        run: npm install -g @openai/codex
      - name: Run Codex Worker
        run: codex --auto "Follow the workflow defined in AGENTS.md and process the pending tasks."
'@
}

foreach ($path in @("ai/tasks/pending/.gitkeep", "ai/tasks/in-progress/.gitkeep", "ai/tasks/done/.gitkeep")) {
    Write-TemplateFile -RelativePath $path -Content "" -OnlyIfMissing
}

foreach ($entry in $templateFiles.GetEnumerator()) {
    # AGENTS.md is handled separately and only created when missing.
    if ($entry.Key -eq "AGENTS.md") { continue }
    Write-TemplateFile -RelativePath $entry.Key -Content $entry.Value -OnlyIfMissing
}

$agentsTemplate = @'
# Codex Repository Agent Rules

This repository uses an AI-driven task workflow.

## Task locations

Pending tasks: ai/tasks/pending
In-progress tasks: ai/tasks/in-progress
Done tasks: ai/tasks/done

## Workflow

1. Process the first task in `ai/tasks/pending`.
2. Move it to `ai/tasks/in-progress`.
3. Implement the task.
4. Validate build and tests.
5. Commit changes.
6. Move task to `ai/tasks/done`.
'@

Write-TemplateFile -RelativePath "AGENTS.md" -Content $agentsTemplate -OnlyIfMissing

if ($DryRun) {
    Write-Host "[DryRun] AI platform seed installation preview completed."
}
else {
    Write-Host "AI platform seed installation completed."
}
